# Generated by Django 4.0.6 on 2022-07-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_store_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='no_copis',
            field=models.IntegerField(null=True),
        ),
    ]
